name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and restart bot on remote server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd hb-reminder-bot && git pull && npm run build
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.password }}
        env:
          CI: true
